#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Control_Cupones")]
public partial class DataClassesCuponDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCupon(Cupon instance);
  partial void UpdateCupon(Cupon instance);
  partial void DeleteCupon(Cupon instance);
  partial void InsertEstado(Estado instance);
  partial void UpdateEstado(Estado instance);
  partial void DeleteEstado(Estado instance);
  partial void InsertDistribuidor(Distribuidor instance);
  partial void UpdateDistribuidor(Distribuidor instance);
  partial void DeleteDistribuidor(Distribuidor instance);
  #endregion
	
	public DataClassesCuponDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Control_CuponesConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesCuponDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesCuponDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesCuponDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesCuponDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Cupon> Cupons
	{
		get
		{
			return this.GetTable<Cupon>();
		}
	}
	
	public System.Data.Linq.Table<Estado> Estados
	{
		get
		{
			return this.GetTable<Estado>();
		}
	}
	
	public System.Data.Linq.Table<Distribuidor> Distribuidors
	{
		get
		{
			return this.GetTable<Distribuidor>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cupon")]
public partial class Cupon : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _Descuento;
	
	private System.Nullable<int> _Distribuidor;
	
	private System.Nullable<int> _Estado;
	
	private System.Nullable<System.DateTime> _Fecha_Expedido;
	
	private System.Nullable<int> _Numero;
	
	private System.Nullable<System.DateTime> _Valido_Hasta;
	
	private EntityRef<Estado> _Estado1;
	
	private EntityRef<Distribuidor> _Distribuidor1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDescuentoChanging(System.Nullable<int> value);
    partial void OnDescuentoChanged();
    partial void OnDistribuidorChanging(System.Nullable<int> value);
    partial void OnDistribuidorChanged();
    partial void OnEstadoChanging(System.Nullable<int> value);
    partial void OnEstadoChanged();
    partial void OnFecha_ExpedidoChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_ExpedidoChanged();
    partial void OnNumeroChanging(System.Nullable<int> value);
    partial void OnNumeroChanged();
    partial void OnValido_HastaChanging(System.Nullable<System.DateTime> value);
    partial void OnValido_HastaChanged();
    #endregion
	
	public Cupon()
	{
		this._Estado1 = default(EntityRef<Estado>);
		this._Distribuidor1 = default(EntityRef<Distribuidor>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Int")]
	public System.Nullable<int> Descuento
	{
		get
		{
			return this._Descuento;
		}
		set
		{
			if ((this._Descuento != value))
			{
				this.OnDescuentoChanging(value);
				this.SendPropertyChanging();
				this._Descuento = value;
				this.SendPropertyChanged("Descuento");
				this.OnDescuentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distribuidor", DbType="Int")]
	public System.Nullable<int> Distribuidor
	{
		get
		{
			return this._Distribuidor;
		}
		set
		{
			if ((this._Distribuidor != value))
			{
				if (this._Distribuidor1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnDistribuidorChanging(value);
				this.SendPropertyChanging();
				this._Distribuidor = value;
				this.SendPropertyChanged("Distribuidor");
				this.OnDistribuidorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
	public System.Nullable<int> Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				if (this._Estado1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnEstadoChanging(value);
				this.SendPropertyChanging();
				this._Estado = value;
				this.SendPropertyChanged("Estado");
				this.OnEstadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Expedido", DbType="DateTime")]
	public System.Nullable<System.DateTime> Fecha_Expedido
	{
		get
		{
			return this._Fecha_Expedido;
		}
		set
		{
			if ((this._Fecha_Expedido != value))
			{
				this.OnFecha_ExpedidoChanging(value);
				this.SendPropertyChanging();
				this._Fecha_Expedido = value;
				this.SendPropertyChanged("Fecha_Expedido");
				this.OnFecha_ExpedidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="Int")]
	public System.Nullable<int> Numero
	{
		get
		{
			return this._Numero;
		}
		set
		{
			if ((this._Numero != value))
			{
				this.OnNumeroChanging(value);
				this.SendPropertyChanging();
				this._Numero = value;
				this.SendPropertyChanged("Numero");
				this.OnNumeroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valido_Hasta", DbType="Date")]
	public System.Nullable<System.DateTime> Valido_Hasta
	{
		get
		{
			return this._Valido_Hasta;
		}
		set
		{
			if ((this._Valido_Hasta != value))
			{
				this.OnValido_HastaChanging(value);
				this.SendPropertyChanging();
				this._Valido_Hasta = value;
				this.SendPropertyChanged("Valido_Hasta");
				this.OnValido_HastaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Cupon", Storage="_Estado1", ThisKey="Estado", OtherKey="Id", IsForeignKey=true)]
	public Estado Estado1
	{
		get
		{
			return this._Estado1.Entity;
		}
		set
		{
			Estado previousValue = this._Estado1.Entity;
			if (((previousValue != value) 
						|| (this._Estado1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Estado1.Entity = null;
					previousValue.Cupons.Remove(this);
				}
				this._Estado1.Entity = value;
				if ((value != null))
				{
					value.Cupons.Add(this);
					this._Estado = value.Id;
				}
				else
				{
					this._Estado = default(Nullable<int>);
				}
				this.SendPropertyChanged("Estado1");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Distribuidor_Cupon", Storage="_Distribuidor1", ThisKey="Distribuidor", OtherKey="Id", IsForeignKey=true)]
	public Distribuidor Distribuidor1
	{
		get
		{
			return this._Distribuidor1.Entity;
		}
		set
		{
			Distribuidor previousValue = this._Distribuidor1.Entity;
			if (((previousValue != value) 
						|| (this._Distribuidor1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Distribuidor1.Entity = null;
					previousValue.Cupons.Remove(this);
				}
				this._Distribuidor1.Entity = value;
				if ((value != null))
				{
					value.Cupons.Add(this);
					this._Distribuidor = value.Id;
				}
				else
				{
					this._Distribuidor = default(Nullable<int>);
				}
				this.SendPropertyChanged("Distribuidor1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado")]
public partial class Estado : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Nombre;
	
	private EntitySet<Cupon> _Cupons;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
	
	public Estado()
	{
		this._Cupons = new EntitySet<Cupon>(new Action<Cupon>(this.attach_Cupons), new Action<Cupon>(this.detach_Cupons));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this.OnNombreChanging(value);
				this.SendPropertyChanging();
				this._Nombre = value;
				this.SendPropertyChanged("Nombre");
				this.OnNombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Cupon", Storage="_Cupons", ThisKey="Id", OtherKey="Estado")]
	public EntitySet<Cupon> Cupons
	{
		get
		{
			return this._Cupons;
		}
		set
		{
			this._Cupons.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Cupons(Cupon entity)
	{
		this.SendPropertyChanging();
		entity.Estado1 = this;
	}
	
	private void detach_Cupons(Cupon entity)
	{
		this.SendPropertyChanging();
		entity.Estado1 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Distribuidor")]
public partial class Distribuidor : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Nombre;
	
	private EntitySet<Cupon> _Cupons;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
	
	public Distribuidor()
	{
		this._Cupons = new EntitySet<Cupon>(new Action<Cupon>(this.attach_Cupons), new Action<Cupon>(this.detach_Cupons));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this.OnNombreChanging(value);
				this.SendPropertyChanging();
				this._Nombre = value;
				this.SendPropertyChanged("Nombre");
				this.OnNombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Distribuidor_Cupon", Storage="_Cupons", ThisKey="Id", OtherKey="Distribuidor")]
	public EntitySet<Cupon> Cupons
	{
		get
		{
			return this._Cupons;
		}
		set
		{
			this._Cupons.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Cupons(Cupon entity)
	{
		this.SendPropertyChanging();
		entity.Distribuidor1 = this;
	}
	
	private void detach_Cupons(Cupon entity)
	{
		this.SendPropertyChanging();
		entity.Distribuidor1 = null;
	}
}
#pragma warning restore 1591
